### PR TITLE
fix: Use `docs.meltano.com` instead of `meltano.com/docs`

### LINKED ISSUE #6635: bug: Some command help text has outdated `meltano.com/docs` links
### Meltano Version

2.4.0

### Python Version

NA

### Bug scope

CLI (options, error messages, logging, etc.)

### Operating System

NA

### Description

Affects 8 links in the Meltano codebase, with one of those being used to generate a few other links in the UI.

### Code

_No response_

### PR DESCRIPTION
**Pull request by WillDaSilva**
Closes #6635

### CODE REVIEW

**Review by edgarrmondragon — APPROVED** [review]

File: src/webapp/src/utils/utils.js [hunk 1]
```diff
@@ -35,7 +35,7 @@ export default {
   docsUrl(path = '/', fragment) {
     fragment = fragment ? `#${fragment}` : ''
 
-    return `https://meltano.com/docs${path}.html${fragment}`
+    return `https://docs.meltano.com/${path}${fragment}`
```
Comment (WillDaSilva) [inline src/webapp/src/utils/utils.js:38]: @alexmarple I'm not sure exactly what this affects, so I'm unsure where to look in the UI to test that the new links are correct. Also, I'm now noticing that there might be an extra slash before `${path}`.

Comment (aaronsteers) [reply src/webapp/src/utils/utils.js:38]: @WillDaSilva - Is it correct that this is just fixing links to docs? Do we know when this broke?

Comment (WillDaSilva) [reply src/webapp/src/utils/utils.js:38]: @aaronsteers It just fixes the links to the docs, not where it's hosted. Here are the spots this change affects:
image

Seems like it's limited to oauth. I wasn't aware there was any oauth in the web UI.

> Do we know when this broke?

These spots in the code haven't been updated in years, which suggests that it was just an oversight when we switched from hosting the docs at `meltano.com/docs` to `docs.meltano.com`.

**Comment by WillDaSilva** [comment]
> Merging [#6636](https://codecov.io/gh/meltano/meltano/pull/6636?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=meltano) ([d0d2e6b](https://github.com/meltano/meltano/commit/d0d2e6b273401fe61f683b3db327fc231905ca9d)) into [main](https://codecov.io/gh/meltano/meltano/commit/b41a2e118205f867b38160b9a862483a2cd929db?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=meltano) ([b41a2e1](https://github.com/meltano/meltano/commit/b41a2e118205f867b38160b9a862483a2cd929db)) will **decrease** coverage by `0.04%`.

I find this a little hard to believe.

**Review by pandemicsyn — APPROVED** [review]

File: src/webapp/src/utils/utils.js (hunk 1 above)
Comment (alexmarple) [reply src/webapp/src/utils/utils.js:38]: @aaronsteers @WillDaSilva This will just fix the url and not break anything.

There is some vestigial oauth stuff and i think this particular util is akin to that. There is a component that uses the util to provide a dynamic link but it's not actually used anywhere anymore.

**Review by alexmarple — APPROVED** [review]
👍

**Review by aaronsteers — APPROVED** [review]
